SPLIT_KEYBOARD = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = yes
TAP_DANCE_ENABLE = yes

LTO_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
